# Numpy Arrays

In [1]:
import numpy as np

def arrays(arr):
    x = np.array(arr, float)[::-1]
    return x
    
arr = input().strip().split(' ')
arr = ['1','2', '3', '4', '-8', '-10']
result = arrays(arr)
print(result)

'1','2', '3', '4', '-8', '-10'
[-10.  -8.   4.   3.   2.   1.]


# Numpy Reshape

In [3]:
import numpy as np

my_array = np.array([1,2,3,4,5,6,7,8,9])

print(np.reshape(my_array,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Numpy Concatenate

In [4]:
import numpy as np

N, M, P = map(int, input().split())

array_N = np.array([input().split() for i in range(N)],int)
array_M = np.array([input().split() for i in range(M)],int)

print(np.concatenate((array_N,array_M), axis = 0))

4 3 2
12
12
12
12
34
34
34
[[12]
 [12]
 [12]
 [12]
 [34]
 [34]
 [34]]


# Numpy Zeros and Ones

In [6]:
import numpy as np

shape = list(map(int, input().split()))

print(np.zeros(shape, dtype = np.int))
print(np.ones(shape, dtype = np.int))

3 3 3 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


C:\Users\Deshmukh\AppData\Local\Temp\ipykernel_10460\1661623171.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.zeros(shape, dtype = np.int))
C:\Users\Deshmukh\AppData\Local\Temp\ipykernel_10460\1661623171.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the rel

# Numpy Eye and Identity

In [7]:
import numpy as np

np.set_printoptions(legacy = '1.13')

N, M = map(int, input().split())

print(np.eye(N, M))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Numpy Array Mathematics

In [8]:
import numpy as np

N, M = map(int, input().split())

arr_N = np.array([list(map(int, input().split())) for n in range(N)])
arr_M = np.array([list(map(int, input().split())) for n in range(N)])

print(arr_N + arr_M)
print(arr_N - arr_M)
print(arr_N * arr_M)
print(arr_N // arr_M)
print(arr_N % arr_M)
print(arr_N ** arr_M)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Numpy Floor, Ceil and Rint

In [10]:
import numpy as np

np.set_printoptions(legacy='1.13')

my_array = list(map(float, input().split()))

print(np.floor(my_array))
print(np.ceil(my_array))
print(np.rint(my_array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Numpy Sum and Prod

In [11]:
import numpy as np

N,M = map(int, input().split())

my_array = np.array([input().split() for i in range(N)],int)

print(np.sum(my_array, axis = 0))
x = np.sum(my_array, axis = 0)
print(np.prod(my_array))
print(np.prod((np.sum(my_array, axis = 0))))

2 2
1 2
3 4
[4 6]
24
24


# Numpy Min and Max

In [13]:
import numpy as np

N,M = map(int, input().split())

my_array = np.array([input().split() for i in range(N)],int)


print(np.min(my_array, axis = 1))
x = np.min(my_array, axis = 1)
print(np.max(x))
print(np.max(np.min(my_array, axis = 1)))

2 4
2 5
3 7
[2 3]
3
3


# Numpy Mean, Var, and Std

In [15]:
import numpy as np

N,M = map(int, input().split())

my_array = np.array([input().split() for i in range(N)],int)


print(np.mean(my_array, axis = 1))
print(np.var(my_array, axis = 0))
x = np.std(my_array, axis = None)
print(round(x, 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Numpy Dot and Cross

In [16]:
import numpy as np

n = int(input())

a = np.array([input().split() for i in range(n)],int)
b = np.array([input().split() for i in range(n)],int)

print(np.dot(a,b))

2
1 2 
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Numpy Inner and Outer

In [17]:
import numpy as np

arr1 = list(map(int, input().split()))
arr2 = list(map(int, input().split()))


print(np.inner(arr1, arr2))
print(np.outer(arr1, arr2))

0 1
2 4
4
[[0 0]
 [2 4]]
